version: '3'
networks:
  metabase_net: # 不使用 default
    external:
      name: ${PROJECT_NAME}-network
services:
  metabase:
    image: metabase/metabase
    container_name: ${PROJECT_NAME}-metabase
    env_file:
      - .env
    ports:
      - ${METABASE_PORT}:3000
    networks:
      - metabase_net          # ← 指向下面这个网络